### ISSUE TITLE
Improper message on missing csslint

### ISSUE THREAD

**Issue by mikebronner** [AtomLinter/linter-csslint#181]
I get this error displayed in the linter tooltip when linting the following CSS:

```css
@import url('./fonts/stylesheet.css');
@import url('https://fonts.googleapis.com/css?family=Raleway');

h1,
h2,
h3,
h4,
h5,
h6,
.widget,
.page-template-template-homepage-php .type-page
{
    font-family: "headings", serif;
}

body,
button,
input,
select,
textarea,
.footer-widgets .widget,
.site-header .site-branding .site-title,
.site-header .site-branding .site-title a,
.widget h1,
.widget h2,
.widget h3,
.widget h4,
.widget h5,
.widget h6,
.sph-hero h1,
.storefront-product-categories ul.products li.product .bistro-category-title-description-wrap h2 mark,
.storefront-product-categories ul.products li.product .bistro-category-title-description-wrap h3 mark,
.storefront-product-categories ul.products li.product .bistro-category-title-description-wrap .woocommerce-loop-product__title mark,
.storefront-product-categories ul.products li.product .bistro-category-title-description-wrap .woocommerce-loop-category__title mark,
.page-template-template-homepage-php .type-page h1,
.page-template-template-homepage-php .type-page h2,
.page-template-template-homepage-php .type-page h3,
.page-template-template-homepage-php .type-page h4,
.page-template-template-homepage-php .type-page h5,
.page-template-template-homepage-php .type-page h6
{
    font-family: "Raleway", sans-serif;
}
```

I checked the developer console, but there were no errors listed there. I ran csslint manually from the command-line on the file and received normal output (no error visible):
```
csslint: There are 31 problems in /Users/mike/Developer/Sites/mt-redesign/public/app/plugins/theme-customizations/style.css.

style.css
1: warning at line 1, col 1
@import prevents parallel downloads, use <link> instead.
@import url('./fonts/stylesheet.css');

style.css
2: warning at line 2, col 1
@import prevents parallel downloads, use <link> instead.
@import url('https://fonts.googleapis.com/css?family=Raleway');

style.css
3: warning at line 24, col 9
Heading (h1) has already been defined.
.widget h1,

style.css
4: warning at line 24, col 9
Heading (h1) should not be qualified.
.widget h1,

style.css
5: warning at line 25, col 9
Heading (h2) has already been defined.
.widget h2,

style.css
6: warning at line 25, col 9
Heading (h2) should not be qualified.
.widget h2,

style.css
7: warning at line 26, col 9
Heading (h3) should not be qualified.
.widget h3,

style.css
8: warning at line 26, col 9
Heading (h3) has already been defined.
.widget h3,

style.css
9: warning at line 27, col 9
Heading (h4) has already been defined.
.widget h4,

style.css
10: warning at line 27, col 9
Heading (h4) should not be qualified.
.widget h4,

style.css
11: warning at line 28, col 9
Heading (h5) has already been defined.
.widget h5,

style.css
12: warning at line 28, col 9
Heading (h5) should not be qualified.
.widget h5,

style.css
13: warning at line 29, col 9
Heading (h6) should not be qualified.
.widget h6,

style.css
14: warning at line 29, col 9
Heading (h6) has already been defined.
.widget h6,

style.css
15: warning at line 30, col 11
Heading (h1) should not be qualified.
.sph-hero h1,

style.css
16: warning at line 30, col 11
Heading (h1) has already been defined.
.sph-hero h1,

style.css
17: warning at line 31, col 95
Heading (h2) should not be qualified.
.storefront-product-categories ul.products li.product .bistro-category-title-description-wrap h2 mark,

style.css
18: warning at line 32, col 95
Heading (h3) should not be qualified.
.storefront-product-categories ul.products li.product .bistro-category-title-description-wrap h3 mark,

style.css
19: warning at line 35, col 49
Heading (h1) should not be qualified.
.page-template-template-homepage-php .type-page h1,

style.css
20: warning at line 35, col 49
Heading (h1) has already been defined.
.page-template-template-homepage-php .type-page h1,

style.css
21: warning at line 36, col 49
Heading (h2) should not be qualified.
.page-template-template-homepage-php .type-page h2,

style.css
22: warning at line 36, col 49
Heading (h2) has already been defined.
.page-template-template-homepage-php .type-page h2,

style.css
23: warning at line 37, col 49
Heading (h3) should not be qualified.
.page-template-template-homepage-php .type-page h3,

style.css
24: warning at line 37, col 49
Heading (h3) has already been defined.
.page-template-template-homepage-php .type-page h3,

style.css
25: warning at line 38, col 49
Heading (h4) has already been defined.
.page-template-template-homepage-php .type-page h4,

style.css
26: warning at line 38, col 49
Heading (h4) should not be qualified.
.page-template-template-homepage-php .type-page h4,

style.css
27: warning at line 39, col 49
Heading (h5) has already been defined.
.page-template-template-homepage-php .type-page h5,

style.css
28: warning at line 39, col 49
Heading (h5) should not be qualified.
.page-template-template-homepage-php .type-page h5,

style.css
29: warning at line 40, col 49
Heading (h6) should not be qualified.
.page-template-template-homepage-php .type-page h6

style.css
30: warning at line 40, col 49
Heading (h6) has already been defined.
.page-template-template-homepage-php .type-page h6

style.css
31: warning
You have 4 h1s, 3 h2s, 3 h3s, 3 h4s, 3 h5s, 3 h6s defined in this stylesheet.
```

Any thoughts on what might be going on? Thanks! :)
