### ISSUE TITLE
Unable to alphabetize vendor prefixes

### ISSUE THREAD

**Issue by jordanallain** [AtomLinter/linter-csslint#216]
I could be mistaken but it seems like whatever order I put these rules in I get the same error.

```css
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif;
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  margin: 0;
  padding: 0;
}
```

<img width="481" alt="screen shot 2019-01-17 at 3 15 08 pm" src="https://user-images.githubusercontent.com/18097107/51346087-b52d2100-1a6a-11e9-9154-d1677274068c.png">

are vendor prefixes accounted for in the alphabetize error?
