### ISSUE TITLE
Unexpected end of input when attempting to lint

### ISSUE THREAD

**Issue by 50Wliu** [AtomLinter/linter-csslint#92]
This only seems to happen on this particular file for whatever reason.

```css
.functionInput{
	width: 67px;
}

.boundInput{
	width: 55px;
}

.rotationInput{
	width: 105px;
}

body{
	font-family: 'Ubuntu', 'Verdana', 'Arial', 'Roboto', 'Open Sans', sans-serif;
	font-size: 14px;
}
```
If you need more info please let me know.  I'm using linter-csslint v1.3.1 along with linter v1.11.3 and Atom 1.7.0-dev-663d9b2.

**Comment by Arcanemagus** [comment]
Hmmm, I'm not able to reproduce this with v1.6.0-beta7. Is there any configuration for `csslint` affecting the file?

Going to try setting up a dev environment for Atom to try to reproduce on that version.

**Comment by Arcanemagus** [comment]
Hmm, can't reproduce with v1.7.0-dev-2bdf4be on Ubuntu 15.10 either.

Can you put a breakpoint [here](https://github.com/AtomLinter/linter-csslint/blob/v1.3.1/lib/main.coffee#L26) and see what `output` contains?

**Comment by Arcanemagus** [comment]
Just to check, tested with 663d9b2 as well, still unable to reproduce :confused:.

**Comment by Arcanemagus** [comment]
As https://github.com/AtomLinter/linter-csslint/issues/93 wasn't showing up for me before, I'll try testing this again when I get home tonight with a blank profile.

**Comment by Arcanemagus** [comment]
Still not able to reproduce this with a blank profile on that version, did you get a chance to set that breakpoint?

**Comment by 50Wliu** [comment]
No, I'll try today.

**Comment by 50Wliu** [comment]
It's completely blank, as in `""`.  And I take back what I said previously - this is happening on every single CSS file now.

**Comment by Arcanemagus** [comment]
How bizarre, but at least I know how to fix this now (put the `JSON.parse()` in a try/catch).

**Comment by Arcanemagus** [comment]
Whoops, this was worked around in #100, although I'm still not sure why it occasionally just returns... _nothing_.

**Comment by Kalcode** [comment]
I am getting the same thing. It was literally working yesterday. Now all my css files throw this error. I havent even updated it since. Confused why its throwing it suddenly. 

I tried uninstalling it and reinstalling and no avail. I think it was the Atom update 1.7.0, since JsHint is having the same error.

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at file:///C:/Users/kalan/.atom/packages/linter-csslint/lib/main.coffee:27:29
    at process._tickCallback (node.js:392:9)
```

```css
.row {
  display: block;
}

.box {
  display: inline-block;
}

```
